services:
  # Web application service
  - type: web
    name: inventaris-telkomsel
    env: docker
    plan: free
    dockerfilepath: Dockerfile
    envVars:
      - key: APP_NAME
        value: "Inventaris Telkomsel"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://inventaris-telkomsel.onrender.com # Change this to your final Render URL
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          databaseName: inventaris-db
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromDatabase:
          databaseName: inventaris-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          databaseName: inventaris-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          databaseName: inventaris-db
          property: password
      - key: APP_KEY
        generateValue: true
      - key: CACHE_STORE
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database

databases:
  # Managed PostgreSQL database service
  - name: inventaris-db
    plan: free
    postgresMajorVersion: 15
