services:
  - type: web
    name: inventaris-telkomsel
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Sistem Manajemen Inventaris
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://inventaris-telkomsel.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: inventaris-db
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromDatabase:
          name: inventaris-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: inventaris-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: inventaris-db
          property: password
      - key: APP_KEY
        generateValue: true
      - key: CACHE_STORE
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database

databases:
  - name: inventaris-db
    plan: free
    databaseName: inventaris_telkomsel
    user: inventaris_user
